### ISSUE TITLE
Looking for different folder structure while launching the sqlnexus.exe

### ISSUE THREAD

**Issue by TomJerry14310164** [microsoft/SqlNexus#104]
![Screenshot_2](https://user-images.githubusercontent.com/78447876/106662981-17cdb880-6571-11eb-845e-e6ac2294dd1a.png)
Please find the screenshot of where it is looking for the files:

at Microsoft.Reporting.WinForms.LocalReport..ctor()
   at Microsoft.Reporting.WinForms.ReportViewer.Reset()
   at Microsoft.Reporting.WinForms.ReportViewer..ctor()
   at sqlnexus.fmNexus.InitializeComponent() in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\fmNexus.Designer.cs:line 79
   at sqlnexus.fmNexus..ctor() in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\fmNexus.cs:line 252
   at sqlnexus.Program.Main(String[] args) in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\Program.cs:line 266

**Comment by PiJoCoder** [comment]
Hello @TomJerry14310164 . Thank you for reporting this. This exception happens due to a missing Report Viewer control. 
Added a fix to handle the exception more gracefully but will not solve the larger problem of a missing control. 
- Could you install the Report Viewer; see [Installation](https://github.com/microsoft/SqlNexus/wiki/Installation)
- Or you can use the PS script to do it for you: [Automated Installation](https://github.com/microsoft/SqlNexus/wiki/Installation#automated-installation-of-prerequisites-requirements)
