### ISSUE TITLE
Importing SQL_Server_Mem_Stats file from SQLLogScout fails with column Object_name does not belong to table

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/SqlNexus#148]
SQLNexus Information: 0 : Opening file C:\temp\log scout\Test 2\output\LAPTOP1_20220323T1038024382_SQL_Server_Mem_Stats.out
    DateTime=2022-03-24T16:11:03.9431168Z
SQLNexus Information: 0 : First time encoutering row identifier 'running memory collector sp_mem_stats15'
    DateTime=2022-03-24T16:11:03.9630198Z
SQLNexus Information: 0 : First time encoutering row identifier '-- query execution memory --'
    DateTime=2022-03-24T16:11:03.9745758Z
SQLNexus Information: 0 : RowsetImportEngine Error: An unexpected error has occurred: 

System.ArgumentException: **Column 'Object_Name' does not belong to table tbl_Query_Execution_Memory.**
   at System.Data.DataRow.GetDataColumn(String columnName)
   at RowsetImportEngine.TextRowsetImporter.InsertRow()
   at RowsetImportEngine.TextRowsetImporter.ProcessFile()

Import cancelled.
    DateTime=2022-03-24T16:11:03.9865946Z
SQLNexus Information: 0 : Flushing rowset tbl_RUNTIMES
    DateTime=2022-03-24T16:11:03.9886873Z
SQLNexus Information: 0 : Flushing rowset tbl_Query_Execution_Memory
    DateTime=2022-03-24T16:11:03.9901925Z
SQLNexus Information: 0 : Rowset Importer failed for file: C:\temp\log scout\Test 2\output\LAPTOP1_20220323T1038024382_SQL_Server_Mem_Stats.outexception: RowsetImportEngine.RowsetImportException: RowsetImport failed. ---> System.ArgumentException: Column 'Object_Name' does not belong to table tbl_Query_Execution_Memory.
   at System.Data.DataRow.GetDataColumn(String columnName)
   at RowsetImportEngine.TextRowsetImporter.InsertRow()
   at RowsetImportEngine.TextRowsetImporter.ProcessFile()
   --- End of inner exception stack trace ---
   at RowsetImportEngine.ErrorDialog.Handle()
   at RowsetImportEngine.TextRowsetImporter.ProcessFile()
   at RowsetImportEngine.TextRowsetImporter.DoImport()
    DateTime=2022-03-24T16:11:03.9901925Z

**Comment by hacitandogan** [comment]
I was checking this old one , I see -- query execution memory -- is now part of PerfStats script  and field Object_Name does not exists there .
@PiJoCoder  Can we consider this as "fixed" ?

**Comment by PiJoCoder** [comment]
> I was checking this old one , I see -- query execution memory -- is now part of PerfStats script and field Object_Name does not exists there . [@PiJoCoder](https://github.com/PiJoCoder) Can we consider this as "fixed" ?

Sounds great, @hacitandogan. Please close. Thank you
