### ISSUE TITLE
Error when installing Nexus 6.0.0.8

### ISSUE THREAD

**Issue by dxico** [microsoft/SqlNexus#67]
Hello 

When i try toi install de Nexus tool, it appears an error:

 **_Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ReportViewer.Common, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Reporting.WinForms.LocalReport..ctor()
   at Microsoft.Reporting.WinForms.ReportViewer.Reset()
   at Microsoft.Reporting.WinForms.ReportViewer..ctor()
   at sqlnexus.fmNexus.InitializeComponent() in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\fmNexus.Designer.cs:line 79
   at sqlnexus.fmNexus..ctor() in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\fmNexus.cs:line 252
   at sqlnexus.Program.Main(String[] args) in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\Program.cs:line 266_**

I already Install de Clrtypes, Reportviewer and RML utilitys

Thanks

Daniel

**Comment by ivaldesMSFT** [comment]
Same issue here. Did you find a solution ?

**Comment by ram2ybabu** [comment]
What is the installed Report viewer version ?

**Comment by ram2ybabu** [comment]
We have released the new version of nexus . The prerequisite section contains the Report viewer version required by SQL nexus. I am closing the issue for now. Please open a new one if you still face the issue.
