### ISSUE TITLE
Installation issues with SQLNexus.6.0.0.8

### ISSUE THREAD

**Issue by saimirjumla** [microsoft/SqlNexus#68]
Installed the CLR, Report Viewer and RML utilities. 
But the installation failing with following error.

@opencode@microsoft.com 
@jackli2000 

Any help is appreciated

PLATFORM VERSION INFO
	Windows 			: 6.3.9600.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2558.0 built by: NET471REL1
	clr.dll 			: 4.7.2563.0 built by: NET471REL1
	dfdll.dll 			: 4.7.2558.0 built by: NET471REL1
	dfshim.dll 			: 6.3.9600.16384 (winblue_rtm.130821-1623)

SOURCES
	Deployment url			: file:///C:/SQLNexus.6.0.0.8/sqlnexus.application
	Application url			: file:///C:/SQLNexus.6.0.0.8/sqlnexus.exe.manifest

IDENTITIES
	Deployment Identity		: sqlnexus.application, Version=6.0.0.8, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil
	Application Identity		: sqlnexus.exe, Version=6.0.0.8, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\SQLNexus.6.0.0.8\sqlnexus.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///C:/SQLNexus.6.0.0.8/nexus.ico.deploy did not succeed.
		+ Could not find file 'C:\SQLNexus.6.0.0.8\nexus.ico.deploy'.
		+ Could not find file 'C:\SQLNexus.6.0.0.8\nexus.ico.deploy'.
		+ Could not find file 'C:\SQLNexus.6.0.0.8\nexus.ico.deploy'.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [22/03/2018 11:40:25] : Activation of C:\SQLNexus.6.0.0.8\sqlnexus.application has started.
	* [22/03/2018 11:40:25] : Processing of deployment manifest has successfully completed.
	* [22/03/2018 11:40:25] : Installation of the application has started.
	* [22/03/2018 11:40:25] : Processing of application manifest has successfully completed.
	* [22/03/2018 11:40:27] : Found compatible runtime version 4.0.30319.
	* [22/03/2018 11:40:27] : Detecting dependent assembly Microsoft.ReportViewer.ProcessingObjectModel, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845DCD8080CC91, processorArchitecture=msil using Microsoft.ReportViewer.ProcessingObjectModel, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=msil.
	* [22/03/2018 11:40:27] : Detecting dependent assembly Microsoft.ReportViewer.DataVisualization, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845DCD8080CC91, processorArchitecture=msil using Microsoft.ReportViewer.DataVisualization, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=msil.
	* [22/03/2018 11:40:27] : Detecting dependent assembly Microsoft.ReportViewer.Common, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845DCD8080CC91, processorArchitecture=msil using Microsoft.ReportViewer.Common, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=msil.
	* [22/03/2018 11:40:27] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [22/03/2018 11:40:27] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///C:/SQLNexus.6.0.0.8/nexus.ico.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\SQLNexus.6.0.0.8\nexus.ico.deploy'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'C:\SQLNexus.6.0.0.8\nexus.ico.deploy'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.FileNotFoundException
		- Could not find file 'C:\SQLNexus.6.0.0.8\nexus.ico.deploy'.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by coffeecanary** [comment]
> OPERATION PROGRESS STATUS
> *[22/03/2018 11:40:25] : Activation of C:\SQLNexus.6.0.0.8\**sqlnexus.application** has started.

In case this helps someone else, I saw this when I accidentally double-clicked sqlnexus.application instead of sqlnexus.exe.

**Comment by PiJoCoder** [comment]
Thank you for reporting this. We apologize for the dealy in responding to these issues. Thanks @coffeecanary  for a lead.
Also, you may be able to get this if not all files have completely downloaded on your system (missing files). Simply download the Release files locally https://github.com/Microsoft/SqlNexus/files/1176948/SQLNexus.6.0.0.8.zip and start using
