### ISSUE TITLE
SQLNexus run from command prompt fails to find SQL Server instance

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/SqlNexus#80]
I tried to run sqlnexus from cmdline according to this https://troubleshootingsql.com/2015/05/12/running-sql-nexus-using-command-line-parameters/ 
 
I ran this on admin cmd window and got error below:
 
D:\SQLNexus.6.0.0.8>sqlnexus.exe /S"serv2\SQL16_SP2" /X /D"sqlnexustest" /I"D:\pssdiag_output\pssdtest\PSSDiagOutput1"
Processing command-line parameters.
 
Command Line Arg (/S): Server="serv2\SQL16_SP2"
Command Line Arg (/X): ExitAfterProcessing
Command Line Arg (/D): Database="sqlnexustest"
Command Line Arg (/I): InputPath="D:\pssdiag_output\pssdtest\PSSDiagOutput1"
Creating Databaseuse master
if db_id ('"sqlnexustest"') is null
begin
        create database ["sqlnexustest"];
        alter database ["sqlnexustest"] modify file (name='"sqlnexustest"', size=50MB)
        alter database ["sqlnexustest"] set recovery simple
end
--else
        -- alter database ["sqlnexustest"] set recovery simple
 
 
Unhandled Exception: System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not access
ible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword,
SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTra
nsientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConn
ection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOption
s userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptio
ns userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, Db
ConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions use
rOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()

**Comment by PiJoCoder** [comment]
Solution:
After working with the person reporting this issue, we found that https://troubleshootingsql.com/2015/05/12/running-sql-nexus-using-command-line-parameters/ was using smart quotes “ ” instead of regular " ". Pasting from it into command line was causing a syntax error for the instance. Once corrected to regular quotes, the issue was resolved. 
Also, feedback was provided to author of the blog and he corrected the issue on his blog post.
