### ISSUE TITLE
SQL Nexus import consistently fails with Violation of PRIMARY KEY constraint 

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/SqlNexus#95]
This seems to happen on every import

System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (f9bbf034-acfe-4c98-ad32-6010573afd3d).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at NexusInterfaces.CSql.ExecuteBatches(String[] batches) in C:\Users\jopilov\Documents\Visual Studio 2015\Projects\Repos\SqlNexus\NexusInterfaces\CSql.cs:line 103
ClientConnectionId:409c1f6e-be73-40b8-addd-aca2cc6f6414
Error Number:2627,State:1,Class:14 
System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (25678531-4722-48c4-94b0-026c2ed1021f).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader()
   at NexusInterfaces.CSql.ExecuteBatches(String[] batches) in C:\Users\jopilov\Documents\Visual Studio 2015\Projects\Repos\SqlNexus\NexusInterfaces\CSql.cs:line 104
ClientConnectionId:409c1f6e-be73-40b8-addd-aca2cc6f6414
Error Number:2627,State:1,Class:14 
System.Data.SqlClient.SqlException (0x80131904): Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (47377ec8-be56-4c92-b0f3-85fc0485d83b).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (fdbf24a1-3ebe-49f1-a02b-fd5686acdae9).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (5e630273-c14f-4dce-bda0-24a1fd8e25ca).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (5ae45557-e463-48d6-b135-11aadcb8642f).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (0c73f3d4-6ccc-4fc9-ae37-58110f9c15db).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (010b3dba-76cc-46c0-ac1b-3cad09f95891).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (6c82da17-d04c-4155-8702-19a9a1363a64).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (6e19b301-e83b-4e5f-af4e-a8dd2251c1b6).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (57caa4bb-c7bd-4f96-8040-3224008a3f39).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (607b17fd-98f1-498e-9b93-f16e5a155730).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (bbecdf81-dcce-4e41-93c9-7eb9e11f53bd).
Violation of PRIMARY KEY constraint 'PK__tbl_Anal__FEB4B4CB7B8E923A'. Cannot insert duplicate key in object 'dbo.tbl_AnalysisSummary'. The duplicate key value is (948756b6-a67f-4cb1-86f9-1b22c26f0b9c).
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.
The statement has been terminated.

**Comment by PiJoCoder** [comment]
Fixed with Commit https://github.com/microsoft/SqlNexus/commit/cfc0a8af0eaccbea26777ea943de77b4c4d4c27b
