### ISSUE TITLE
CLR Types install points to 2012 when 2016 Required

### ISSUE THREAD

**Issue by cbattlegear** [microsoft/SqlNexus#99]
https://github.com/microsoft/SqlNexus/wiki/Installation

CLR Types install direct links to 2012 CLR Types install which is incompatible with the 2016 report viewer.

**Comment by steinem23** [comment]
I am having an issue with the install. I have tried installing the following packages together with no luck:

Report Viewer 2012 + CLR 2012
Report Viewer 2015 + CLR 2014

I don't see an install for Report Viewer 2016 on the Microsoft site.

I am getting the following error:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ReportViewer.Common, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Reporting.WinForms.LocalReport..ctor()
   at Microsoft.Reporting.WinForms.ReportViewer.Reset()
   at Microsoft.Reporting.WinForms.ReportViewer..ctor()
   at sqlnexus.fmNexus.InitializeComponent() in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\fmNexus.Designer.cs:line 79
   at sqlnexus.fmNexus..ctor() in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\fmNexus.cs:line 252
   at sqlnexus.Program.Main(String[] args) in C:\Users\jackli\Documents\GitHub\Sqlnexus\sqlnexus\Program.cs:line 266
```

What do I need to do to fix this?

Thanks

**Comment by cbattlegear** [comment]
The 2016 version of the Report Viewer Control can be downloaded from this page currently: https://www.microsoft.com/en-us/download/details.aspx?id=56833

Click download and scroll down to report viewer, you can also find the 2016 version of the CLR types there to download also.

**Comment by PiJoCoder** [comment]
@cbattlegear THANK YOU for reporting this. It is now fixed. Appreciate it.
